name: UX Problem
description: Report a problem with the user experience when using Supposition.jl
title: "[UX]: "
labels: ["UX"]
body:
  - type: markdown
    attributes:
      value: |
        If you have a usage question, please search or post to the [Discussions tab](https://github.com/Seelengrab/Supposition.jl/discussions).
        We use the GitHub issue tracker for bug reports, UX problems and feature development only.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the steps you took and provide any code executed to reproduce the bug, as well as any error messages that were printed.
      placeholder: |
        I executed this function:
        
        ```julia
        [...]
        ````
  
        and encountered the following bad UX:
  
        [...]
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: How could this be communicated better?
      description: Please provide a suggestion on how the (un-)desirable result can be communicated better.
      placeholder: It would be easier to read the result, if it were formatted like [...] or had more space around [...].
    validations:
      required: true
  - type: textarea
    id: julia-version
    attributes:
      label: Julia Version
      description: What version of julia are you running?
      placeholder: In the environment the bug occurred, please run `using InteractiveUtils; versioninfo()` and paste the output here.
      render: shell
    validations:
      required: true
  - type: textarea
    id: package-environment
    attributes:
      label: Package Environment
      description: What version of Supposition.jl are you using?
      placeholder: In the environment the bug occurred, please run `import Pkg; Pkg.status()` and paste the output here.
      render: shell
    validations:
      required: true
